// This file is automatically generated by generate_script_manager.py from CMake

#pragma once
#include "ntshengn_script_manager.h"

#include "camerascript.h"
#include "objectscript.h"

NtshEngn::Scriptable NtshEngn::ScriptManager::createScriptable(const std::string& scriptName) {
	Scriptable scriptable;

	if (scriptName == "CameraScript") { scriptable.script = createScript<CameraScript>(); }
	else if (scriptName == "ObjectScript") { scriptable.script = createScript<ObjectScript>(); }

	return scriptable;
}

extern "C" NTSHENGN_SCRIPT_MANAGER_API NtshEngn::ScriptManagerInterface* createScriptManager() {
	return new NtshEngn::ScriptManager;
}

extern "C" NTSHENGN_SCRIPT_MANAGER_API void destroyScriptManager(NtshEngn::ScriptManagerInterface* sm) {
	delete sm;
}